runtime: nodejs18
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: dist/viewer-app/\1
  upload: dist/viewer-app/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: dist/viewer-app/index.html
  upload: dist/viewer-app/index.html